---
version: '3'
services:
  prometheus:
    container_name: prometheus
    image: ${PROM_IMAGE:-prom/prometheus:v2.5.0}
    ports:
      - 127.0.0.1:9090:9090
    network_mode: host
    volumes:
      - ./prometheus/linux.yml:/etc/prometheus/prometheus.yml
    command: ["--config.file=/etc/prometheus/prometheus.yml",
              "--storage.tsdb.path=/prometheus",
              "--storage.tsdb.retention=5m",
              "--web.console.libraries=/usr/share/prometheus/console_libraries",
              "--web.console.templates=/usr/share/prometheus/consoles"]

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter
    ports:
      - 127.0.0.1:9100:9100
    network_mode: host

  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server
    ports:
      - 127.0.0.1:8123:8123
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9009:9009
    network_mode: host
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml

  clickhouse_exporter:
    container_name: clickhouse_exporter
    image: f1yegor/clickhouse-exporter
    ports:
      - 127.0.0.1:9116:9116
    network_mode: host
    command: -scrape_uri=http://127.0.0.1:8123/

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 127.0.0.1:3000:3000
    network_mode: host
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning

  tabix:
    container_name: tabix
    image: spoonest/clickhouse-tabix-web-client
    ports:
      - 127.0.0.1:8080:80
    network_mode: host
